output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks_cluster.cluster_endpoint
}

output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.eks_cluster.cluster_id
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = module.eks_cluster.cluster_name
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks_cluster.cluster_security_group_id
}

output "oidc_provider_arn" {
  description = "ARN of the OIDC Provider for the EKS cluster"
  value       = module.eks_cluster.oidc_provider_arn
}

output "kubectl_config" {
  description = "kubectl config as generated by the aws_eks_cluster module"
  value       = module.eks_cluster.kubectl_config
  sensitive   = true
}

output "vpc_id" {
  description = "ID of the VPC created for the EKS cluster"
  value       = module.eks_cluster.vpc_id
}

output "private_subnet_ids" {
  description = "IDs of the private subnets created for the EKS cluster"
  value       = module.eks_cluster.private_subnet_ids
}

output "public_subnet_ids" {
  description = "IDs of the public subnets created for the EKS cluster"
  value       = module.eks_cluster.public_subnet_ids
}

output "oidc_provider_url" {
  description = "URL of the OIDC Provider for the EKS cluster (without https://)"
  value       = module.eks_cluster.oidc_provider_url
}