output "cluster_id" {
  description = "EKS cluster ID"
  value       = aws_eks_cluster.infra-cluster.id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.infra-cluster.endpoint
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = aws_eks_cluster.infra-cluster.vpc_config[0].cluster_security_group_id
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = aws_eks_cluster.infra-cluster.name
}

output "oidc_provider_arn" {
  description = "ARN of the OIDC Provider for the EKS cluster"
  value       = aws_iam_openid_connect_provider.eks_oidc.arn
}

output "kubectl_config" {
  description = "kubectl config as generated by the aws_eks_cluster module"
  value       = <<KUBECONFIG
apiVersion: v1
clusters:
- cluster:
    server: ${aws_eks_cluster.infra-cluster.endpoint}
    certificate-authority-data: ${aws_eks_cluster.infra-cluster.certificate_authority[0].data}
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "${aws_eks_cluster.infra-cluster.name}"
KUBECONFIG
  sensitive   = true
}

output "vpc_id" {
  description = "ID of the VPC created for the EKS cluster"
  value       = aws_vpc.main.id
}

output "private_subnet_ids" {
  description = "IDs of the private subnets created for the EKS cluster"
  value       = aws_subnet.private[*].id
}

output "public_subnet_ids" {
  description = "IDs of the public subnets created for the EKS cluster"
  value       = aws_subnet.public[*].id
}

output "oidc_provider_url" {
  description = "URL of the OIDC Provider for the EKS cluster (without https://)"
  value       = local.eks_oidc_issuer_url
}